#!/usr/bin/python3
"""Generate a reviewed candidate overlay outside the checkout; never launch it."""
import argparse
import json
from pathlib import Path
import sys
HERE=Path(__file__).resolve().parent
sys.path.insert(0,str(HERE))
import gpui_probe


def prepare(baseline,manifest,output):
    original,_,_=gpui_probe.frozen_probe.preflight(baseline)
    baseline=baseline.resolve();manifest=manifest.resolve();output=output.resolve()
    root=Path(original['output_root']).resolve()
    if root not in output.parents or output.exists():
        raise RuntimeError('overlay must be a new file in the frozen dedicated evidence root, outside source')
    verification=gpui_probe.verify_current_candidate(manifest)
    build=json.loads(manifest.read_text())
    if build.get('source_consistent') is not True:
        raise RuntimeError('candidate source was inconsistent during build')
    binary=build['binary'];app=Path(binary['path']).resolve()
    if not app.is_file() or gpui_probe.sha(app)!=binary['sha256']:
        raise RuntimeError('candidate binary differs from reviewed build manifest')
    overlay={'schema_version':1,'kind':'gpui-ime-overlay','baseline_deployment':str(baseline),
        'baseline_deployment_sha256':gpui_probe.sha(baseline),'candidate':{
        'app':{'path':str(app),'sha256':binary['sha256']},
        'manifest':{'path':str(manifest),'sha256':gpui_probe.sha(manifest)}}}
    with output.open('x') as f:f.write(json.dumps(overlay,ensure_ascii=False,indent=2)+'\n')
    try:gpui_probe.preflight(output,current=True)
    except Exception:
        # Retain invalid generated bytes for diagnosis; never report them valid.
        raise
    return overlay


def main():
    p=argparse.ArgumentParser(description=__doc__);p.add_argument('--baseline',type=Path,default=HERE/'deployment.lock.json')
    p.add_argument('--candidate-manifest',type=Path,required=True);p.add_argument('--output',type=Path,required=True)
    a=p.parse_args();value=prepare(a.baseline,a.candidate_manifest,a.output)
    print(json.dumps({'prepared_deployment':str(a.output.resolve()),'candidate':value['candidate'],'native_executed':False},indent=2))

if __name__=='__main__':main()
